### ISSUE TITLE
[请求] 全附魔启用/禁用支持

### ISSUE THREAD

**Issue by Rad233** [the-doo/X-Enchantment#31]
很感谢你对社区的贡献，这是个很棒的模组！如果能添加全附魔的启用/禁用支持，我相信这个模组还能更好。原因如下：
    有的附魔过于强大，比如“聪慧”，在没有“随时间强化怪物”的情况下，玩家可以通过挂机来获取大量经验，这间接鼓励了玩家挂机，而非探索；有的附魔与其他模组的附魔效果相同（而那个模组并没有提供对应的禁用支持）。
    此外，完全的附魔启用/禁用支持也可以让整合包作者更好地进行平衡性调整，由此，这个模组的平衡性会更好。

    模组创作不易，模组开发完成后的善后工作更是繁杂。这个请求可能完成并不容易，因此，如果需要一些经济上的支持，请私信我的bilibili账号（根号Radical），我会尽己所能地提供协助。

**Comment by the-doo** [comment]
1.20以后才支持全面禁用
