### ISSUE TITLE
请求全附魔启用/禁用支持1.18.2

### ISSUE THREAD

**Issue by moyuguguji** [the-doo/X-Enchantment#33]
您好,请问能在1.18.2支持全附魔启用/禁用吗,现在无限:重生整合包的更新真的很需要这个,以及加了Improvedmobs之后怪物身上有弑君者附魔装备有可能崩端
[错误报告-2023-8-2_19.28.53.zip](https://github.com/the-doo/X-Enchantment/files/12240779/-2023-8-2_19.28.53.zip)

**Comment by moyuguguji** [comment]
好的,辛苦了

**Comment by SmallYii** [comment]
> 好的，不过由于之前的代码结构，可能全配置会比较麻烦，我应该是直接用现有结构去向下实现，所以如果你着急我可以先发给你一个修复这个bug的一样版本，而不出现在curseforge等之类的公开库中 [X-Enchantment-1.18-1.18-8.8.zip](https://github.com/the-doo/X-Enchantment/files/12245212/X-Enchantment-1.18-1.18-8.8.zip)
> 
> 需要将后缀改成.jar直接覆盖就行了

请问可以添加对潜龙在渊附魔的配置吗？ 可以调整潜龙在渊的最大附魔等级，最高5倍武器面板伤害对于魔改整合包来说有点太强了，谢谢

**Comment by the-doo** [comment]
额，所有配置相关的问题，旧版本不会再对其修改了，除非是有bug会提供修复版本，不好意思哈

**Comment by moyuguguji** [comment]
那能给一个禁掉部分附魔的版本吗?弑君者,身高优势,潜龙在渊这几个

**Comment by the-doo** [comment]
我可以给你一个不注册的版本，你需要告诉我哪几个附魔你是不需要的

**Comment by moyuguguji** [comment]
弑君者,身高优势,潜龙在渊,百步穿杨,无限增强,夜影克星,多谢了

**Comment by the-doo** [comment]
需要将后缀改成.jar直接覆盖就行了
[X-Enchantment-1.18-1.18-8.8.zip](https://github.com/the-doo/X-Enchantment/files/12326575/X-Enchantment-1.18-1.18-8.8.zip)

**Comment by moyuguguji** [comment]
好的,辛苦了,请问能留个QQ号什么的吗?以后有问题好联系点
