### ISSUE TITLE
拾取距离会增加？

### ISSUE THREAD

**Issue by wsxiya** [the-doo/X-Enchantment#34]
即使什么附魔都不附，人物的拾取距离会比原版更远，物品距离两格就会拾取进入背包

**Comment by the-doo** [comment]
你好，能帮忙截一下当前玩家信息的具体值吗（tab键会出来的面板），还有就是当前的游戏版本跟加载器版本，谢谢了

**Comment by wsxiya** [comment]
> 你好，能帮忙截一下当前玩家信息中Attribute页面的具体值吗（tab键会出来的面板），还有就是当前的游戏版本跟加载器版本，谢谢了

游戏版本为1.20.1，forge版本为47.1.3，mod版本为1.0.9,按TAB什么都不会显示呀

**Comment by wsxiya** [comment]
> 你好，能帮忙截一下当前玩家信息中Attribute页面的具体值吗（tab键会出来的面板），还有就是当前的游戏版本跟加载器版本，谢谢了

而且只有物品和玩家在一个平面时，拾取距离才会比原版更远

**Comment by the-doo** [comment]
查证，该问题为PlayerInfo的问题，目前最新版本1.0.8.1已经解决
